import { useState } from 'react';
import { StyleSheet, Text, View, Pressable } from 'react-native';
import { AppHeader, BottomNav, JourneyScreen, PaperCard, PrimaryButton } from '@/components/JourneyUI';
import { Colors } from '@/constants/Colors';
import { worlds } from '@/data/journey';

export default function AssignScreen() {
  const [selected, setSelected] = useState<string[]>(['bits-accion']); const [assigned, setAssigned] = useState(false);
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id]);
  return <JourneyScreen scroll={false} style={styles.screen}><View style={styles.main}><AppHeader title="Asignar misión" /><Text style={styles.lead}>Selecciona una misión para tu clase</Text><PaperCard><Text style={styles.world}>Mundo 1 · Código secreto</Text>{worlds[0].missions.map((mission, index) => <Pressable key={mission.id} onPress={() => toggle(mission.id)} style={styles.item}><View style={[styles.radio, selected.includes(mission.id) && styles.radioActive]}>{selected.includes(mission.id) && <Text style={styles.check}>✓</Text>}</View><Text style={styles.itemText}>{index + 1}. {mission.title}</Text></Pressable>)}</PaperCard><Text style={styles.label}>Clase</Text><PaperCard style={styles.field}><Text style={styles.fieldText}>2°A Secundaria</Text><Text>⌄</Text></PaperCard><Text style={styles.label}>Fecha límite</Text><PaperCard style={styles.field}><Text style={styles.fieldText}>30/07/2026</Text><Text>▣</Text></PaperCard><View style={{ flex: 1 }} />{assigned && <View style={styles.success}><Text style={styles.successTitle}>✓ Misión asignada</Text><Text style={styles.successText}>27 estudiantes recibirán la actividad.</Text></View>}<PrimaryButton secondary label={assigned ? 'Asignada correctamente' : `Asignar ${selected.length} misión${selected.length === 1 ? '' : 'es'}`} disabled={!selected.length || assigned} onPress={() => setAssigned(true)} /></View><BottomNav teacher /></JourneyScreen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, main: { flex: 1, paddingHorizontal: 18, paddingBottom: 15 }, lead: { color: Colors.inkSoft, textAlign: 'center', fontSize: 12, marginTop: -6, marginBottom: 18 }, world: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 17, fontWeight: '700', marginBottom: 7 }, item: { flexDirection: 'row', minHeight: 45, alignItems: 'center', borderTopWidth: 1, borderTopColor: Colors.line }, radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: Colors.line, alignItems: 'center', justifyContent: 'center', marginRight: 10 }, radioActive: { backgroundColor: Colors.teal, borderColor: Colors.teal }, check: { color: Colors.white, fontSize: 12, fontWeight: '800' }, itemText: { color: Colors.ink, fontSize: 13 }, label: { color: Colors.ink, fontWeight: '800', marginTop: 16, marginBottom: 6, fontSize: 12 }, field: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12 }, fieldText: { color: Colors.ink, fontWeight: '700' }, success: { backgroundColor: '#DCE5C2', borderRadius: 12, padding: 12, marginBottom: 10 }, successTitle: { color: Colors.ink, fontWeight: '800' }, successText: { color: Colors.inkSoft, fontSize: 11, marginTop: 2 } });
