import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, BottomNav, JourneyScreen, PaperCard, ProgressBar, Stat } from '@/components/JourneyUI';
import { Colors } from '@/constants/Colors';
import { guides } from '@/data/journey';
import { useJourney } from '@/lib/JourneyContext';

export default function ProfileScreen() {
  const { completed, guide, stars, xp, resetJourney } = useJourney(); const activeGuide = guides.find((g) => g.id === guide) ?? guides[0];
  return <JourneyScreen scroll={false} style={styles.screen}><View style={styles.main}><AppHeader title="Tu perfil" /><PaperCard style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>🧑🏽‍🚀</Text></View><Text style={styles.name}>Explorador</Text><Text style={styles.level}>Nivel {Math.floor(completed.length / 4) + 1} · Guía {activeGuide.name}</Text><ProgressBar value={(xp % 100) || 10} /><Text style={styles.xp}>{xp} / 100 XP</Text></PaperCard><PaperCard style={styles.stats}><Stat icon="★" value={stars} label="Estrellas" /><View style={styles.divider} /><Stat icon="◉" value={completed.length} label="Rachas" /><View style={styles.divider} /><Stat icon="✓" value={completed.length} label="Misiones" /></PaperCard><PaperCard><Text style={styles.cardTitle}>Constelación personal</Text><View style={styles.constellation}><Text style={styles.lines}>✦ ── · ── ✦{`\n`}     ╲      ╱{`\n`}       ✦ ── ·</Text></View></PaperCard><Pressable onPress={() => { resetJourney(); router.replace('/'); }}><Text style={styles.reset}>Cambiar de explorador</Text></Pressable></View><BottomNav /></JourneyScreen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, main: { flex: 1, paddingHorizontal: 18 }, identity: { alignItems: 'center', marginTop: 8 }, avatar: { width: 82, height: 82, borderRadius: 41, backgroundColor: '#E7A650', alignItems: 'center', justifyContent: 'center', marginTop: -6 }, avatarText: { fontSize: 50 }, name: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 24, fontWeight: '700', marginTop: 7 }, level: { color: Colors.inkSoft, fontSize: 12, marginVertical: 5 }, xp: { color: Colors.inkSoft, fontSize: 10, marginTop: 4 }, stats: { flexDirection: 'row', paddingVertical: 5, marginVertical: 12 }, divider: { width: 1, backgroundColor: Colors.line, marginVertical: 9 }, cardTitle: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 17, fontWeight: '700', textAlign: 'center' }, constellation: { height: 106, alignItems: 'center', justifyContent: 'center' }, lines: { color: Colors.orange, fontFamily: 'Courier', fontSize: 20, lineHeight: 25 }, reset: { color: Colors.orange, fontWeight: '700', textAlign: 'center', padding: 16, fontSize: 12 } });
