import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, BottomNav, JourneyScreen, PaperCard, PrimaryButton } from '@/components/JourneyUI';
import { Colors } from '@/constants/Colors';

export default function ResourcesScreen() {
  const [tab, setTab] = useState(0); const [notice, setNotice] = useState('');
  const tabs = ['Guía docente', 'Actividades offline', 'Extras'];
  return <JourneyScreen scroll={false} style={styles.screen}><View style={styles.main}><AppHeader title="Recursos para la clase" /><View style={styles.tabs}>{tabs.map((item, index) => <Pressable key={item} onPress={() => setTab(index)} style={[styles.tab, tab === index && styles.tabActive]}><Text style={[styles.tabText, tab === index && styles.tabTextActive]}>{item}</Text></Pressable>)}</View>{tab === 0 && <><PaperCard style={styles.resource}><Text style={styles.icon}>📖</Text><Text style={styles.title}>Guía docente</Text><Text style={styles.description}>Explicación paso a paso, objetivos de aprendizaje y posibles preguntas para acompañar cada mundo.</Text><PrimaryButton secondary label="Ver guía" onPress={() => setNotice('Guía abierta para consulta')} /></PaperCard><PaperCard style={styles.resource}><Text style={styles.icon}>🪢</Text><Text style={styles.title}>Actividad offline</Text><Text style={styles.description}>Descarga una actividad de quipus binarios para trabajar sin internet.</Text><PrimaryButton secondary label="Preparar PDF" onPress={() => setNotice('PDF preparado para descargar')} /></PaperCard></>}{tab === 1 && <PaperCard style={styles.resource}><Text style={styles.icon}>✂️</Text><Text style={styles.title}>Kit de constelaciones</Text><Text style={styles.description}>Tarjetas imprimibles para representar bits, probabilidades y mediciones en grupo.</Text><PrimaryButton secondary label="Ver actividad" onPress={() => setNotice('Actividad lista para imprimir')} /></PaperCard>}{tab === 2 && <PaperCard style={styles.resource}><Text style={styles.icon}>✦</Text><Text style={styles.title}>Glosario cuántico</Text><Text style={styles.description}>Definiciones cercanas y ejemplos andinos para presentar vocabulario nuevo.</Text><PrimaryButton secondary label="Abrir glosario" onPress={() => setNotice('Glosario abierto')} /></PaperCard>}{notice ? <Text style={styles.notice}>✓ {notice}</Text> : null}</View><BottomNav teacher /></JourneyScreen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, main: { flex: 1, paddingHorizontal: 18 }, tabs: { flexDirection: 'row', marginTop: 7, marginBottom: 14, gap: 5 }, tab: { flex: 1, paddingVertical: 9, borderRadius: 10, backgroundColor: Colors.paperDeep, alignItems: 'center' }, tabActive: { backgroundColor: Colors.orange }, tabText: { color: Colors.inkSoft, fontSize: 9, fontWeight: '700', textAlign: 'center' }, tabTextActive: { color: Colors.white }, resource: { marginBottom: 12 }, icon: { fontSize: 32 }, title: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 20, fontWeight: '700', marginTop: 6 }, description: { color: Colors.inkSoft, fontSize: 12, lineHeight: 18, marginTop: 6, marginBottom: 13 }, notice: { color: Colors.green, fontWeight: '800', textAlign: 'center', marginTop: 10 } });
