import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, BottomNav, JourneyScreen, PaperCard, PrimaryButton, Stat } from '@/components/JourneyUI';
import { Colors } from '@/constants/Colors';

export default function TeacherHome() {
  return <JourneyScreen scroll={false} style={styles.screen}><View style={styles.main}><AppHeader title="Bienvenido, Profe" right={<Text style={styles.avatar}>👨🏽‍🏫</Text>} /><Text style={styles.name}>Profe Andino</Text><PaperCard style={styles.stats}><Stat icon="✦" value={2} label="Clases" /><Stat value={18} label="Estudiantes" /><Stat value={6} label="Misiones activas" /></PaperCard><Text style={styles.section}>Clases recientes</Text><Pressable onPress={() => router.push('/class/2a')}><PaperCard style={styles.classCard}><View><Text style={styles.className}>2°A Secundaria</Text><Text style={styles.meta}>27 estudiantes · 72% de progreso</Text></View><Text style={styles.chevron}>›</Text></PaperCard></Pressable><Pressable onPress={() => router.push('/class/3b')}><PaperCard style={styles.classCard}><View><Text style={styles.className}>3°B Secundaria</Text><Text style={styles.meta}>40 estudiantes · 64% de progreso</Text></View><Text style={styles.chevron}>›</Text></PaperCard></Pressable><View style={styles.actions}><PrimaryButton secondary label="Nueva clase" onPress={() => router.push('/class/2a')} /></View><Text style={styles.tip}>Consejo del día</Text><PaperCard><Text style={styles.tipTitle}>Conecta lo nuevo con lo cercano</Text><Text style={styles.tipText}>Usa quipus, caminos y constelaciones para introducir ideas abstractas antes de formalizarlas.</Text></PaperCard></View><BottomNav teacher /></JourneyScreen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, main: { flex: 1, paddingHorizontal: 18 }, avatar: { fontSize: 27 }, name: { color: Colors.ink, fontFamily: 'Georgia', fontWeight: '700', fontSize: 21, marginTop: 5 }, stats: { flexDirection: 'row', marginTop: 13, paddingVertical: 5 }, section: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 18, fontWeight: '700', marginTop: 20, marginBottom: 9 }, classCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 }, className: { color: Colors.ink, fontWeight: '800' }, meta: { color: Colors.inkSoft, fontSize: 11, marginTop: 4 }, chevron: { color: Colors.inkSoft, fontSize: 25 }, actions: { marginTop: 3 }, tip: { color: Colors.orange, fontWeight: '800', fontSize: 11, letterSpacing: 1, marginTop: 22, marginBottom: 7 }, tipTitle: { color: Colors.ink, fontWeight: '800' }, tipText: { color: Colors.inkSoft, fontSize: 12, lineHeight: 17, marginTop: 5 } });
