import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, BottomNav, JourneyScreen, PaperCard, ProgressBar } from '@/components/JourneyUI';
import { Colors } from '@/constants/Colors';
import { students } from '@/data/journey';

export default function ClassScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [tab, setTab] = useState<'progress' | 'missions' | 'students'>('progress');
  const title = id === '3b' ? '3°B Secundaria' : '2°A Secundaria';
  return <JourneyScreen scroll={false} style={styles.screen}><View style={styles.main}><AppHeader title={title} back /><View style={styles.tabs}>{(['progress', 'missions', 'students'] as const).map((key) => <Pressable key={key} onPress={() => setTab(key)} style={[styles.tab, tab === key && styles.tabActive]}><Text style={[styles.tabText, tab === key && styles.tabTextActive]}>{key === 'progress' ? 'Progreso' : key === 'missions' ? 'Misiones' : 'Estudiantes'}</Text></Pressable>)}</View>{tab === 'progress' && <><PaperCard style={styles.overview}><View style={styles.ring}><Text style={styles.ringValue}>72%</Text></View><View style={{ flex: 1 }}><Text style={styles.big}>72%</Text><Text style={styles.meta}>Promedio de misiones completadas</Text></View></PaperCard><Text style={styles.section}>Misiones más desafiantes</Text>{['2. Contar en binario', '3. Bits en acción', '4. Reto final'].map((item, index) => <PaperCard key={item} style={styles.challenge}><Text style={styles.challengeTitle}>{item}</Text><View style={styles.bar}><ProgressBar value={[26, 60, 42][index]} /></View><Text style={styles.percent}>{[26, 60, 42][index]}%</Text></PaperCard>)}</>}{tab === 'students' && <View style={styles.studentList}>{students.map((student, i) => <PaperCard key={student.name} style={styles.student}><Text style={styles.studentAvatar}>{['👩🏽','👨🏽','👩🏾','👨🏻','👩🏻'][i]}</Text><View style={{ flex: 1 }}><Text style={styles.studentName}>{student.name}</Text><ProgressBar value={student.progress} /></View><View><Text style={styles.studentXp}>{student.xp} XP</Text><Text style={styles.studentProgress}>{student.progress}%</Text></View></PaperCard>)}</View>}{tab === 'missions' && <View style={styles.studentList}>{['El quipu digital', 'Bits en acción', 'Contar en binario'].map((item, i) => <Pressable key={item} onPress={() => router.push('/assign')}><PaperCard style={styles.student}><View style={styles.missionNum}><Text style={styles.missionNumText}>{i + 1}</Text></View><View style={{ flex: 1 }}><Text style={styles.studentName}>{item}</Text><Text style={styles.meta}>{i === 0 ? 'Asignada · vence mañana' : 'Disponible para asignar'}</Text></View><Text style={styles.chevron}>›</Text></PaperCard></Pressable>)}</View>}</View><BottomNav teacher /></JourneyScreen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 0 }, main: { flex: 1, paddingHorizontal: 18 }, tabs: { flexDirection: 'row', backgroundColor: Colors.paperDeep, borderRadius: 12, padding: 4, marginTop: 5 }, tab: { flex: 1, paddingVertical: 9, borderRadius: 9, alignItems: 'center' }, tabActive: { backgroundColor: Colors.paper }, tabText: { color: Colors.inkSoft, fontSize: 11, fontWeight: '700' }, tabTextActive: { color: Colors.orange }, overview: { flexDirection: 'row', alignItems: 'center', gap: 18, marginTop: 18 }, ring: { width: 92, height: 92, borderRadius: 46, borderWidth: 12, borderColor: Colors.teal, alignItems: 'center', justifyContent: 'center' }, ringValue: { color: Colors.ink, fontWeight: '800', fontSize: 18 }, big: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 27, fontWeight: '700' }, meta: { color: Colors.inkSoft, fontSize: 11, marginTop: 4 }, section: { color: Colors.ink, fontFamily: 'Georgia', fontSize: 18, fontWeight: '700', marginTop: 24, marginBottom: 9 }, challenge: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, marginBottom: 8 }, challengeTitle: { color: Colors.ink, fontSize: 12, fontWeight: '700', width: 130 }, bar: { flex: 1 }, percent: { color: Colors.ink, fontWeight: '800', fontSize: 11, marginLeft: 8 }, studentList: { marginTop: 16, gap: 8 }, student: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 11 }, studentAvatar: { fontSize: 31 }, studentName: { color: Colors.ink, fontWeight: '800', marginBottom: 5 }, studentXp: { color: Colors.orange, fontWeight: '800', fontSize: 10 }, studentProgress: { color: Colors.inkSoft, fontSize: 10, textAlign: 'right', marginTop: 3 }, missionNum: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.orange, alignItems: 'center', justifyContent: 'center' }, missionNumText: { color: Colors.white, fontWeight: '800' }, chevron: { color: Colors.inkSoft, fontSize: 23 } });
